#!/bin/bash

echo
printf "%-20s %-6s %-10s %s\n" "HOST" "PORT" "STATUS" "BANNER"
echo "-------------------------------------------------------------------------------"

while read -r line; do
    [[ -z "$line" || "$line" != *:* ]] && continue

    host="${line%%:*}"
    port="${line##*:}"

    result=$(powershell -NoProfile -Command "
param([string]\$h,[int]\$p)

try {
    \$client = New-Object System.Net.Sockets.TcpClient
    \$client.Connect(\$h,\$p)
    \$stream = \$client.GetStream()

    if (\$p -eq 22) {
        \$reader = New-Object System.IO.StreamReader(\$stream)
        \$banner = \$reader.ReadLine()
        Write-Output \"OPEN|\$banner\"
    }
    elseif (\$p -eq 80 -or \$p -eq 8080) {
        \$writer = New-Object System.IO.StreamWriter(\$stream)
        \$writer.Write(\"GET / HTTP/1.1`r`nHost: \$h`r`nConnection: close`r`n`r`n\")
        \$writer.Flush()
        \$reader = New-Object System.IO.StreamReader(\$stream)
        \$line = \$reader.ReadLine()
        Write-Output \"OPEN|\$line\"
    }
    else {
        Write-Output \"OPEN|No banner\"
    }

    \$client.Close()
}
catch {
    Write-Output \"CLOSED|\"
}
" -Args "$host","$port")

    status="${result%%|*}"
    banner="${result#*|}"

    printf "%-20s %-6s %-10s %s\n" "$host" "$port" "$status" "$banner"

done < targets.txt
